### PR TITLE
improved style of shortcut buttons

### LINKED ISSUE #852: improve style of shortcut buttons
see #801

### PR DESCRIPTION
**Pull request by plata**
fixes #852

default

breeze dark

unity

### CODE REVIEW

**Comment by plata** [comment]
@madoar it seems like the default button theme from Unity overrides `shortcutButton` from the default theme. That's a bit strange for me.

**Comment by qparis** [comment]
Lot better

**Comment by madoar** [comment]
@plata you mean previous to your PR? The changes look like you added an override^^
I guess it would be enough to only override the property `-fx-border-color:transparent;`

**Comment by plata** [comment]
Sorry my mistake.

**Pull request merged**
