### PR TITLE
Fixed again, previous link was pointing to phoenicis not PlayOnLinux

### PR DESCRIPTION
**Pull request by Ads20000**
Apologies @qparis

### CODE REVIEW

**Comment by Ads20000** [comment]
Oh, no, ignore this, sorry, looks like @plata is shaking things up

**Comment by Ads20000** [comment]
I'm really sorry, I wasn't keeping an eye on what was going on, though @plata 's link is currently a dead one because the Phoenicis GitHub doesn't exist yet. Also what's the reasoning behind the name change?

**Comment by plata** [comment]
The reasoning behind the name change is the following:
Currently, we have PlayOnLinux and PlayOnMac. In the future, we might also get PlayOnAndroid/PlayOnMobile. However, all these programs are in fact the same software. So we want one unified brand including everything.

Regarding the Phoenicis GitHub: I changed that by mistake (batch rename). I'm not sure if @qparis is planning to move POL-POM-5 to a Phoenicis repository (maybe in a Phoenicis organization). It would make totally sense in my opinion. If not, we should merge your fix. @Ads20000 please fix the link to the build instructions in wiki.

@qparis reopened for you to take a decision ;)

**Comment by judge2020** [comment]
fixed with #578

**Pull request closed without merging**
