### PR TITLE
use ThemeManager to load button icons

### PR DESCRIPTION
**Pull request by plata**

### CODE REVIEW

**Comment by plata** [comment]
I did it to be consistent with the category icons. However, I'm not sure if this is really a good idea: If the icons are not specified in CSS, they also do not change when the theme changes.

**Comment by plata** [comment]
Ok. So if we do it like this, how do we update the icons when the theme is changed? Or do we just say that you have to restart?

**Comment by qparis** [comment]
If you want this, you will need an event handling mechanism.
You could create a ThemeResource class with two attributes: 
- resourceUrl
- Set<Runnable> onUrlChange

**Comment by plata** [comment]
To be honest, I don't really need it. I was just wondering if people would expect it.

**Comment by qparis** [comment]
I think indeed it is not a must to have

**Comment by plata** [comment]
Fine. Should we add a label to the settings page stating "Please restart to apply the new icon theme?"

**Comment by qparis** [comment]
Yes good idea

**Comment by plata** [comment]
Ok. Will do that.

**Pull request merged**
