### PR TITLE
Removing Observer/Observable

### PR DESCRIPTION
**Pull request by Tomahna**
Replacing remainings references to Observer/Observable by consumer based systems

### CODE REVIEW

**Comment by Tomahna** [comment]
Looks like PlayOnLinuxBOT was asleep for this one.

**Comment by qparis** [comment]
ok to test

**Comment by qparis** [comment]
Very good work!

**Comment by qparis** [comment]
Can you fix the conflict? Thanks

**Comment by Tomahna** [comment]
Conflict fixed

**Pull request merged**
