### PR TITLE
Switch to URI objects for the repository paths inside the Repositories

### LINKED ISSUE #696: Error when adding a local repository, whose path contains a space character
Currently it leads to a POL 5 software freeze, and a corrupted `config.properties` file, if you add a `LocalRepository`, whose directory path contains a space (" ") character. 
This happens, because the Java `URI` class can't handle space characters.

### PR DESCRIPTION
**Pull request by madoar**
This PR fixes #696.
In a nutshell it changes the repository URL/path `String` objects to `URI` objects. This enables us to load local repositories, whose path contains "illegal" characters like spaces.

Sadly this currently leads to an exception when loading a `ClasspathRepository`:
```
[ForkJoinPool.commonPool-worker-2] WARN org.phoenicis.apps.repository.ClasspathRepository - Error while reading resource directory
java.io.FileNotFoundException: class path resource [/org/phoenicis/repository/] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:187)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.findPathMatchingResources(PathMatchingResourcePatternResolver.java:419)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.getResources(PathMatchingResourcePatternResolver.java:287)
	at org.phoenicis.apps.repository.ClasspathRepository.fetchInstallableApplications(ClasspathRepository.java:57)
	at java.util.stream.Collectors.lambda$toConcurrentMap$59(Collectors.java:1473)
	at java.util.stream.ReferencePipeline.lambda$collect$1(ReferencePipeline.java:496)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
Interestingly the tests in `ClasspathRepositoryTest` work...

### CODE REVIEW

**Comment by plata** [comment]
Is the `ClasspathRepository` working after the last commit?

**Comment by madoar** [comment]
Sry forgot to add a comment here. Yes, it's working now, I basically threw my changes to the `ClasspathRepository` out of the window. I think it's the best idea to use a String inside the `ClasspathRepository` like we currently do.

**Comment by plata** [comment]
It's ok for me then. Would like @qparis to have a look at the changes in `ConfigurableRepository`.

**Comment by madoar** [comment]
Just to make this more clear: there are no changes done to `ConfigurableRepository`.
I simply deleted it, because we're not using it.

**Pull request merged**
