### PR TITLE
use safe beans for UI factories

### LINKED ISSUE #939: cannot start and uninstall app
```
[pool-4-thread-4] ERROR org.phoenicis.multithreading.ControlledThreadPoolExecutorService - java.lang.IllegalAccessError: You are not allowed to instanciate uiQuestionFactory (of class org.phoenicis.javafx.views.scriptui.JavaFxUiConfiguration$$Lambda$479/1908057566) from a script.
	at org.phoenicis.scripts.nashorn.builtins.BeanInjector.fetchBean(BeanInjector.java:35)
```

@qparis I think this has been introduced by #914

### PR DESCRIPTION
**Pull request by plata**
fixes #939

### CODE REVIEW

**Comment by plata** [comment]
I don't know what I should write into the JavaDoc. That it's the JavaFX implementation of the interface? I think that's clear.

**Comment by qparis** [comment]
CLI implantations also need to be marked safe

**Comment by madoar** [comment]
I would like to have the information in there, that the `SetupUiFactoryJavaFX` is for setup windows and `UiQuestionFactoryJavaFX` for ui question dialogs.
I'm not sure what the third class supplies, therefore I ask for javadoc^^

**Comment by plata** [comment]
@madoar I think that information should rather be in the interface.

**Comment by madoar** [comment]
@qparis as far as I understand his changes, he also extracted the factories for the cli implementation.
Take a look at the classes:
- `ProgressUiFactoryCLI`
- `SetupUiFactoryCLI`
- `UiQuestionFactoryCLI`

**Pull request merged**
