### PR TITLE
allow apps in a separate "Apps" directory

### PR DESCRIPTION
**Pull request by plata**

### CODE REVIEW

**Comment by qparis** [comment]
I don't understand the purpose of this commit

**Comment by plata** [comment]
Currently, the apps categories and the functions folder are in the same directory. In my opinion this should be separated.

**Comment by qparis** [comment]
Why?

**Comment by plata** [comment]
Because the functions are no apps. They only do not show up in the Apps tab because they do not contain a category.json. I would prefer if you could look at the repository and can tell immediately where the installable applications are.

**Comment by qparis** [comment]
Why not... But I think that your commit is going to break javascript include function

**Comment by plata** [comment]
Don't know. I installed Notepad++ with the configuration and it worked.

**Comment by plata** [comment]
Maybe it would even make sense to move the engines from functions to an "Engines" directory at top level. This would emphasize the similarity between apps and engines as it can also be found in the GUI (at least when #620 is implemented).

**Comment by qparis** [comment]
With this code, fetchCategories() will no longer return functions, and I'm not 100% sure that it is ok

**Comment by plata** [comment]
It will. It only searches the Apps directory additionally. Moreover, I don't understand why it should return functions. After all, Functions is not an app category so why should the ApplicationsSource fetch it?

**Comment by qparis** [comment]
Because this is how include is designed

**Comment by plata** [comment]
Ok. Can you tell me where this is implemented? (just want to understand it)

**Comment by plata** [comment]
Found it. ScriptFetcher.getScript right? Wouldn't it be more logical to call the ApplicationsSource RepositorySource if it fetches applications, engines and functions?

**Comment by qparis** [comment]
This is not strange. You need to imagine that you can call any script for any script. This is the idea of the structure.
What you want to implement is a 4-level namespace instead of a 3-level one. I think it really makes sense, but the whole problem should be thought about. For example, ClassPathApplicationSource also needs to be updated. The DTO set also has to be updated

**Comment by plata** [comment]
Don't get me wrong: I don't think it's strange that there is a class which fetches the scripts in the repository. My concern was that this class is called `ApplicationsSource` which suggests that it fetches only applications.
To be honest, I didn't really realize the implications of this PR. But maybe it would really make sense to switch to 4-level as you say (before we have so many apps that it's too hard to handle this). I don't know about the `ClassPathApplicationsSource` but the DTO should be rather easy: Just a new top level DTO which distinguishes functions, apps etc.

**Comment by plata** [comment]
Seems to work like this. The Functions folder contains another Functions folder. If you know a better naming, let me know ;)

**Comment by qparis** [comment]
Shall we close this Pull request?

**Comment by plata** [comment]
Superseded by  #745.

**Pull request closed without merging**
