### PR TITLE
use StyleManager to change theme

### LINKED ISSUE #536: [Themes] Theme doesn't change
Theme doesn't change immediately after selecting a theme and pressing `Save`. I would expect it to change immediately.

Unity theme...but it's not
Dark theme...but it's not

### LINKED ISSUE #542: [Themes] Theme dialogs
Dialogs create a new stage, so we cannot just assign a style class.

See: <https://stackoverflow.com/questions/28417140/styling-default-javafx-dialogs>

### PR DESCRIPTION
**Pull request by plata**
- fixes #542 
dialog

- fixes #536

There is an issue with tabs:
tabs

@qparis do you have an idea what I need to do to fix this?

### CODE REVIEW

**Comment by qparis** [comment]
Non idea. Isn't it a regression?

**Comment by plata** [comment]
Yes it is. But I don't know why it behaves differently than before.

**Comment by qparis** [comment]
It must be related with your CSS refactoring commit

**Comment by plata** [comment]
No. It's related to the SceneManger somehow (did not change Breeze Dark in the refactoring commit).

**Pull request merged**
