### PR TITLE
Breeze Dark: dark background for installation

### LINKED ISSUE #496: Small white line below left image in step representation
white line

### PR DESCRIPTION
**Pull request by plata**
fixes #496

Somehow, I have problems changing the text color. Could need some help there.
text-color

### CODE REVIEW

**Comment by qparis** [comment]
Does the text has a className?

**Comment by plata** [comment]
No. I would think that it should use the default text color of `.text {` but it doesn't.

**Comment by qparis** [comment]
Well you may try to add a class then

**Comment by plata** [comment]
Don't know if it's a good idea to have so many classes. In the end, you have to fine tune everything when you just want to change the text color...

**Comment by qparis** [comment]
You can add -fx-fill: #FFF; to the root pane I guess then

**Comment by plata** [comment]
I tried that already. Doesn't work.

**Comment by qparis** [comment]
I think we could replace
 
.leftPaneCheckBox .text {
    -fx-fill: #eff0f1;
}

with

.text {
    -fx-fill: #eff0f1;
}

And then, add the text class in StepRepresentationMessage

**Comment by plata** [comment]
Ok. I think we should consider specifying colors and fonts on a higher level than the individual node in general. Currently, there are also different fonts used throughout the application etc.

**Comment by qparis** [comment]
Oops forgot to squash

**Comment by plata** [comment]
That's why I said change the settings ;)

**Pull request merged**
