### PR TITLE
Revert "Hide scrollbar"

### PR DESCRIPTION
**Pull request by plata**
Reverts PlayOnLinux/POL-POM-5#440

Doesn't build.

### CODE REVIEW

**Comment by Brainzyy** [comment]
@plata Don't revert the whole commit. Just remove the 'q' after the ';' on line 56.

**Comment by plata** [comment]
@Brainzyy I cannot change the pull request. @qparis has to do it.

**Comment by qparis** [comment]
My mistake sorry.

**Comment by qparis** [comment]
Can you just remove the scroll bar as I did before? It is a really little change

**Comment by plata** [comment]
see #442

**Pull request merged**
