### PR TITLE
gray scale for not installed wine versions

### LINKED ISSUE #602: Mark installed engines
E.g. by adding a green check
installed

### PR DESCRIPTION
**Pull request by plata**
fixes #602 

grayscale

### CODE REVIEW

**Comment by plata** [comment]
@qparis I'm not quite sure about the way I check if the version is installed. I assume it should be done in JS, right? But then, where do I put the Java method to access this? I would expect WineVersionsManager but this seems to be used for available versions only.

**Comment by qparis** [comment]
We could extend this piece of code

**Comment by plata** [comment]
The WineVersionsManager? If so, should we rename it to WineManager?

**Comment by qparis** [comment]
WineEnginesManager

**Comment by qparis** [comment]
But maybe this should also be scriptable

**Comment by plata** [comment]
What do you have in mind?

**Comment by qparis** [comment]
I don't understand why using WineManager

**Comment by plata** [comment]
How would you do it?

**Comment by qparis** [comment]
I mean, why do you want to remove "Version" from the name?

**Comment by plata** [comment]
I was thinking that we need an interface in Java to access the Wine JS. As this is more than just querying versions, a more general name would be better.

**Comment by qparis** [comment]
On the contrary, I think that everything related to wine should be written in JS as it is more customizable

**Comment by plata** [comment]
Ok, but I need to access this somehow from Java. Or should this be done in the controller directly?

**Comment by qparis** [comment]
Why?

**Comment by plata** [comment]
I need the information whether or not a certain version is installed to show it in ViewEngines. So somehow I must be able to access this data.

**Comment by qparis** [comment]
We are already accessing getAllWineVersions() from Java.

But I really think that in the long run, Java should be wine agnostic and all interfaces should be implemented in JS

**Comment by plata** [comment]
Are you talking about `getAvailableVersions()`? That's not what I need.

I think I get your point. You want something similar to ShortcutReader, right?

**Comment by qparis** [comment]
I'd like to go even further. We should define an complete interface describing what an engine is, what a container is, and what a shortcut is. Then, we could implement it in JS for every kind of engine

**Comment by plata** [comment]
Ok. But that's now a completely separate issue (can you create a new issue for this?). 

For this implementation now: Should I leave it as it is or implement `isEngineInstalled()` in JS?

**Comment by qparis** [comment]
You can implement is installed engine

**Comment by plata** [comment]
Ok. Is it ok to do it later and merge this first? I'm working on the filter as well so it would be easier to merge the current implementation for both first and then fix it with `isEngineInstalled()` together later on.

**Pull request merged**
