### PR TITLE
added categories for settings

### LINKED ISSUE #519: [Settings] Create diffirent categories
Use the left pane to create different categories: 
* User interface
** Theme
* Repositories
* File association
* Network
** HTTP proxies

...

### PR DESCRIPTION
**Pull request by plata**
fixes #519 

categories

ui

### CODE REVIEW

**Comment by qparis** [comment]
Great!
Can we just add a title and some icons, to be consistent?

**Comment by plata** [comment]
Sure. I had used "Settings" as title before but that looks strange because the whole tab is already called "Settings". So what should I write there? Which icon should I use?

**Comment by plata** [comment]
icons

**Comment by plata** [comment]
icon per category

**Comment by qparis** [comment]
Settings is OK

**Comment by plata** [comment]
title

**Pull request merged**
