### PR TITLE
disable next button if no text entered in wizard

### PR DESCRIPTION
**Pull request by plata**
see #540

### CODE REVIEW

**Comment by qparis** [comment]
What if I want to ask something that is not mandatory?

**Comment by plata** [comment]
Might happen. However, I do not really see a use case right now. If it is required at some point, we could just add another `textbox()` function specifying that it's optional.

Like
```javascript
var userText = setupWizard.textbox(message, default, optional);
```

**Comment by qparis** [comment]
I like the first solution

**Comment by qparis** [comment]
Why not allowing to pass a regex?

**Comment by plata** [comment]
We could also pass a function which return true/false when it's given a string (thus determining whether or not the "Next" button is enabled).
Nevertheless, none of those really belongs to this PR so I would like if you could merge this such that the original error is fixed. We can then have a new issue to implement the optional textbox (if you believe that it is needed).

**Comment by qparis** [comment]
Actually I'm pretty sure that we will need it, but ok.

**Pull request merged**
