### PR TITLE
fixed missing title in details panel

### LINKED ISSUE #865: title missing in details panel
see #862

### PR DESCRIPTION
**Pull request by plata**
fixes #865 

title

### CODE REVIEW

**Comment by qparis** [comment]
Can you add little margins so that the title is aligned with the rest?

**Comment by plata** [comment]
I don't know (this is done in the base class so it might not work in all places).

**Comment by madoar** [comment]
This looks like something is overriding the style of the base class.
Take a look at the other tabs, for example the "Apps" tab, there you'll discover that the margins are larger. 
This is the reason why I previously wrote we need to refactor the details tabs, because some of them are defining their of css classes, which makes them look not uniform.

**Comment by plata** [comment]
In this case we should not do this within this PR.

**Comment by plata** [comment]
What happened to Jenkins?

**Comment by plata** [comment]
run tests

**Comment by madoar** [comment]
Hmm, it seems like we get a timeout inside the `AppConfigurationTest`:
```
java.util.concurrent.TimeoutException
	at org.phoenicis.javafx.AppConfigurationInitialisationTest.testAppConfigurationInitialisation(AppConfigurationInitialisationTest.java:21)
```
@qparis is there anything you can do about this?

**Comment by qparis** [comment]
There were some problems with Jenkins yesterday. Should be fixed

**Comment by plata** [comment]
Should be ok to merge now.

**Pull request merged**
