### PR TITLE
implemented fallback to default theme

### PR DESCRIPTION
**Pull request by plata**

### CODE REVIEW

**Comment by qparis** [comment]
We need to have a SkinManager component if we want to handle this properly

**Comment by plata** [comment]
Well at least it does not crash if you have a non existing theme in your user settings. Instead it shows an error message and falls back to the default theme.

**Comment by qparis** [comment]
It will still crash when the application description is shown which is even worse because you won't understand why.
This is why I suggest to create a bean responsible of providing the theme resources

**Comment by plata** [comment]
#510

**Pull request closed without merging**
