### PR TITLE
Bugfix: Added missing default values for the viewsources property

### PR DESCRIPTION
**Pull request by madoar**
Added the missing default value for the new `viewsource` property.
See the comments on commit 4b08e122ae034459e614939d398a2f4a6a774387 for details.

### CODE REVIEW

**Comment by plata** [comment]
ok to test

**Comment by plata** [comment]
@qparis we should have a test in Jenkins to find errors like this before the merge.

**Comment by qparis** [comment]
Which test?

**Comment by plata** [comment]
I don't know. Some kind of system test which at least checks that the application does not crash on startup.

**Pull request merged**
