### PR TITLE
Unity refinements

### PR DESCRIPTION
**Pull request by plata**
@Ads20000 like this?

checkbox

button and combobox

I tried to change the tabs but it doesn't look good.

### CODE REVIEW

**Comment by qparis** [comment]
There is a weird white bar above left pane title. Is it expected?

**Comment by plata** [comment]
@qparis that's the search field.

**Comment by Ads20000** [comment]
Wow, that's amazing! Yeah the tabs would be difficult to get right, it's pretty good as it is!

**Comment by Ads20000** [comment]
@plata One more thing, would it be possible to get this:
screenshot from 2017-01-29 01-28-57
to also work like this:
screenshot from 2017-01-29 01-29-11
Getting it to go orange when selected?

**Comment by Ads20000** [comment]
@plata and another thing... The dialogue screen for adding a repository needs Ubuntufying
screenshot from 2017-01-29 01-32-50

**Comment by plata** [comment]
Regarding toggle buttons for categories: this has been discussed in #520. 

I know about the dialog issue and I have tried to theme that for Breeze Dark already. However, I could not get it working. If I can figure it out, the theme can be enhanced of course.

**Pull request merged**
