### PR TITLE
Replaced byte[] with icon and miniature data in ApplicationDTO and ShortcutDTO with URI objects

### PR DESCRIPTION
**Pull request by madoar**
This PR replaces the byte arrays, that contain the image data corresponding to shortcuts and applications with `URI` objects.
The result now looks like this:
grafik
grafik
grafik
grafik

I know that the proportions are a bit off now. It would be nice if someone can correct them at a later time.

A follow up PR should concentrate on the problem with the ShortcutDTO content.
When a `ShortcutDTO` is created, it receives the `URI` objects from the corresponding `ApplicationDTO` object. Only after a restart at a later time the URI will be corrected to link to a copy of the icon/miniature that belongs to the shortcut.

### CODE REVIEW

**Comment by madoar** [comment]
After replacing cover with contain in `-fx-background-size` POL 5 looks like this:
grafik
grafik
grafik
grafik

**Comment by plata** [comment]
I like it. Why do we need `appMiniature` and `miniatureImage`?

**Comment by madoar** [comment]
To set the sizes of the images. If you don't have them the images are either to large or too small.
If you can get it working without them that's also fine :)

**Comment by plata** [comment]
My question rather was why we need both of them. Is there anything special about the miniatures for apps?

**Comment by madoar** [comment]
`appMiniature` is for the miniature inside the `AppPanel`, which you see after you've clicked on an application in the Apps tab.
`miniatureImage` is for the miniature inside the `MiniatureListWidget`.

**Comment by plata** [comment]
Ah ok. Don't forget to update the wiki with that information.

**Comment by madoar** [comment]
Do you want to merge this now, or do you want to wait for @qparis?

**Comment by plata** [comment]
I would like to wait for @qparis (I don't know if he had any special plans with the byte[]).

**Comment by madoar** [comment]
Another needed follow up PR for this one is to clean up the css classes for the miniature list widget.
Some classes are missing some important definitions, like `.miniatureText` which is missing `-fx-pref-width` and `-fx-pref-height`. 
Other classes contradict each other, like `.miniatureListElement` and `.miniatureImage` with their different `-fx-background-radius`, `-fx-pref-width` and `-fx-pref-height` attributes.

**Comment by qparis** [comment]
This has already been discussed before. 
A DTO should not contain an URI, because this is not properly serializable. The ObjectMapper won't work anymore and we won't be able to use them to create webservices for instance

**Comment by plata** [comment]
The CategoryDTO stores the icon path in a String. How's that supposed to work then?

**Comment by qparis** [comment]
A string is fine, a URI is not serializable (afaik)

**Comment by plata** [comment]
So we can just replace the URI by a String?

**Comment by plata** [comment]
According to the [docs](https://docs.oracle.com/javase/8/docs/api/java/net/URI.html) URI implements Serializable. That's not sufficient?

**Comment by qparis** [comment]
Not sure that jackson will accept it

**Comment by madoar** [comment]
I guess it can (see https://github.com/FasterXML/jackson-databind/issues/908) but I'm not sure how well.

**Comment by madoar** [comment]
Even if we don't use URIs in the DTOs, we'll still need to use them somewhere, because we need them to scale the images in the miniature list widget and the AppPanel. 
I'm not sure how to do this elegantly otherwise...

**Comment by madoar** [comment]
@qparis, is there an easy way to test if jackson can do this?

**Comment by plata** [comment]
@madoar if we store the URI as String, everything should work fine (just like for CategoryDTO).

**Comment by madoar** [comment]
If possible I would like to not convert the URI to a String internally, because it needs an additionally possibly unnecessary step in between and because we're losing a part of the type safety when doing that.

But you're right, we should have this option in mind, if jackson really can't serialize URI objects.

**Comment by qparis** [comment]
It seems that jackson accepts URI objects

**Pull request merged**
