### PR TITLE
handle tr(null) correctly

### LINKED ISSUE #901: Playonlinux can't connect with repositories.
Playonlinux can't connect with repositories.
When I click on apps or engines tab, I see load indicator for a long time but nothing happens.
aa

### PR DESCRIPTION
**Pull request by plata**
fixes #901

### CODE REVIEW

**Comment by plata** [comment]
Does this test even run with the build? It doesn't seem so.

**Comment by qparis** [comment]
You have to follow the other tests pattern

**Comment by plata** [comment]
I think I did that. It's the same as `testTrWithAString`.

**Comment by qparis** [comment]
You are right. So it should run

**Comment by madoar** [comment]
Hmm, when looking at http://www.playonlinux.org:8080/job/POL-POM-5_PullRequest/935/org.phoenicis$phoenicis-configuration/console it doesn't seem like the tests are run...

**Comment by madoar** [comment]
Ok I believe I know the reason...
Take a look at the content of the `src/test` folder in the `phoenicis-configuration` project, it doesn't contain a `java` subfolder.
As far as I know, per maven default all tests must be located in `src/test/java`.

**Comment by qparis** [comment]
Right. Can you fix it?

**Comment by madoar** [comment]
I think it's best if this is fixed in this PR, so I think @plata should insert the `java` folder.

**Pull request merged**
