### PR TITLE
fixed padding of side bar buttons in Unity theme

### PR DESCRIPTION
**Pull request by plata**
padding

### CODE REVIEW

**Comment by madoar** [comment]
I'm not sure, but shouldn't the `SearchBox` have a padding too?

**Comment by plata** [comment]
No. It's on purpose that it takes the complete width of the side bar.

**Comment by madoar** [comment]
Ok. After you've fixed the conflict I'll approve this PR.

**Comment by madoar** [comment]
Or @qparis does it :P

**Comment by madoar** [comment]
One more idea: what about an orange border for the list widget selection?

**Comment by plata** [comment]
I will try it.

**Comment by plata** [comment]
Doesn't look so good. The problem is that the border should have some radius but then it doesn't surround the icon well (because the icon has some shadow).

**Comment by madoar** [comment]
What about using `-fx-background-color` and `-fx-background-radius` as an alternative for `-fx-border-color` and `-fx-border-radius`?

**Comment by plata** [comment]
Also tried that. But than the icon gets a strange color as it is opaque.

**Comment by madoar** [comment]
Ok, then let's stay with the current approach, it was worth a try ;)

**Pull request merged**
