### PR TITLE
 	show engine tools in TilePane

### LINKED ISSUE #933: Wine tool tabs are displayed incorrectly.
zrzut ekranu z 2017-06-28 11-58-28

### PR DESCRIPTION
**Pull request by plata**
fixes #933

tile pane

### CODE REVIEW

**Comment by madoar** [comment]
How does the layout react, if you make the window smaller?

**Comment by plata** [comment]
You cannot change the width of the right panel currently.

**Comment by madoar** [comment]
You're right you can't explicitly change the width of the details panel, but you can implicitly change it by changing the width of the whole window.
In the current version, if you take a look at the not maximized window you'll discover that the details view looks kind of clipped, i.e. the close button isn't shown. I believe the reason for this may be solved by this PR.

**Comment by plata** [comment]
If you make the whole window smaller than the right panel, it's still clipped. However, I have the impression that this is not caused by the TilePane but rather by the containing tab (it happens even with a FlowPane).

**Comment by madoar** [comment]
One of the contained tabs in the details pane is too large.
This makes the whole details pane too large.

**Comment by plata** [comment]
I'm not sure. Maybe it's just the preferred width?

**Comment by madoar** [comment]
I did some experiments some weeks prior, and as far as I remember the reason was a too large tab.

**Comment by plata** [comment]
Do you know which one? I can't see which tab is that big. However, also the close icon is not visible anymore, so this does not relate to this PR (we should fix it nevertheless).

**Pull request merged**
