### PR TITLE
removed some unused imports

### PR DESCRIPTION
**Pull request by herochao**
removed all unused Imports listed on http://qparis.net:9000/component_issues/index?id=com.playonlinux:playonlinux#resolved=false|rules=squid%3AUselessImportCheck 

Is there a more general place to ask questions/discuss them?
I'd like to work on the GTK implementation of the interface. How can i test the other UI Implementations?

### CODE REVIEW

**Comment by yawkat** [comment]
Is this really necessary? Just looks like diff pollution

**Comment by qparis** [comment]
Yes it is necessary to make this kind of effort to maintain a clean code. It is more important to have clean codebase than clean history.

Thank you :-)

**Comment by qparis** [comment]
Ok to test

**Comment by qparis** [comment]
You can contact us on #playonlinux-dev on freenode

**Comment by qparis** [comment]
Ok to test

**Pull request merged**
