### PR TITLE
split creation of RepositoryDTO in MockRepository

### PR DESCRIPTION
**Pull request by plata**

### CODE REVIEW

**Comment by qparis** [comment]
I don't understand the point of this PR
This won't exempt us from fixing the formatter issue in my opinion

**Comment by plata** [comment]
Maybe not. But on the other hand the structure got quite complex and wasn't well understandable anymore. Now it should be clearer what's going on. As a side effect, the formatting does not look so strange anymore.

**Comment by qparis** [comment]
To be honnest, I find this a lot more easier to read:

**Comment by qparis** [comment]
Same problem for Spring configuration: 
capture d ecran 2017-06-05 a 15 57 11

vs. 

capture d ecran 2017-06-05 a 15 57 29

**Comment by qparis** [comment]
Also equals() and hashCode() ...
capture d ecran 2017-06-05 a 15 58 28
vs.
capture d ecran 2017-06-05 a 15 58 43

**Comment by qparis** [comment]
I think you got my point

**Comment by plata** [comment]
I agree that the second formatting looks better. I just don't know enough about the settings to get this behavior. I just wouldn't like to remove the formatter completely because that will totally mess up the code on the long run.

**Comment by plata** [comment]
Maybe this: <https://stackoverflow.com/questions/7166795/can-eclipse-formatter-wrap-where-necessary-every-element-on-a-new-line>

**Comment by plata** [comment]
Can you try if you prefer:
```xml
<setting id="org.eclipse.jdt.core.formatter.join_wrapped_lines" value="false"/>
```
That should keep a line wrap.

**Comment by qparis** [comment]
Sounds that it is what we need

**Comment by madoar** [comment]
How is the current state of this PR?

**Pull request closed without merging**
