### PR TITLE
asynchronous update for containers

### PR DESCRIPTION
**Pull request by plata**
fixes: 
- App hangs when switching from and to containers #470
- Container main window doesn't get refreshed after uninstall #469

### CODE REVIEW

**Comment by qparis** [comment]
I still have the problem

**Comment by plata** [comment]
Do you have any explanation? I did the same as for apps but couldn't really test as I do not have the problem.

**Comment by qparis** [comment]
It comes from the fact that fetchContainers() is called multiple times at once. 
However, you configured _containersExecutorService_ so that its queue has a size of one. Therefore, this executor service will lock the sender thread until the queue is released.

Few solutions: 
- Increase the size of the queue
- Investigate why fetchContainers() is called multiple times at once

**Comment by plata** [comment]
Strange. I had outputs in `fetchContainers()` and I got the output only once when PoL was started and then once when I opened the "Containers" tab.
Feel free to resize the queue. I don't know which number might reasonable here.

**Comment by qparis** [comment]
Try to switch quickly from one tab to another

**Comment by plata** [comment]
Ok. Well in this case what's happening is that your fetch is slower than you are switching tabs. How many prefixes do you have? Do you have a SSD?

I don't know if it is possible to fetch only when switching to "Containers" (currently it's also done when leaving "Containers").

**Comment by qparis** [comment]
I have 15 prefixes with potentially large registry files. Yes I do have a SSD

**Comment by plata** [comment]
Is it necessary to read the registry?

**Comment by qparis** [comment]
Yes, if you want to know the current settings value (like GLSL, windows version, etc...)

**Comment by plata** [comment]
But that would be enough once you select a container.

**Comment by qparis** [comment]
Yes but much more complicated to implement. You would need to define two different types of DTO

**Comment by plata** [comment]
True. But like this you're potentially reading a lot of files you never need.

**Comment by plata** [comment]
#473 should at least reduce the load a bit.

**Pull request merged**
