### PR TITLE
made presentation styleable

### LINKED ISSUE #515: make StepRepresentationPresentation themeable

### PR DESCRIPTION
**Pull request by plata**
default

breeze dark

fixes #515

Might need some fine tuning in the CSS later on.

### CODE REVIEW

**Comment by qparis** [comment]
The text is too close from the borders

**Comment by plata** [comment]
I know. But when I add padding, it makes a white border. No idea where that is coming from.

**Comment by qparis** [comment]
Can you show?

**Comment by plata** [comment]
padding

**Comment by qparis** [comment]
Maybe we could try to put the pane into a borderPane

**Comment by plata** [comment]
I have it... Wrong CSS parameter.

**Comment by plata** [comment]
default

breeze dark

**Pull request merged**
