### PR TITLE
Fix #842 and improve shortcut properties presentation

### LINKED ISSUE #842: ObjectMapper does not work in all cases
When you show certain apps (e.g. Age of Empires II HD) in the `LibraryPanel`, you get
```
[JavaFX Application Thread] WARN org.phoenicis.javafx.views.mainwindow.library.LibraryPanel - Could not parse shortcut script JSON
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: {"type":"WINE","wineDebug":"-all","winePrefix":"Age of Empires II HD","arguments":["-silent","-applaunch",221380],"workingDirectory":"/home/plata/.Phoenicis/wineprefix/Age of Empires II HD/drive_c/Program Files/Steam","executable":"/home/plata/.Phoenicis/wineprefix/Age of Empires II HD/drive_c/Program Files/Steam/Steam.exe"}; line: 1, column: 83] (through reference chain: java.util.LinkedHashMap["arguments"])
```

This is a regression because the previous solution worked.

### PR DESCRIPTION
**Pull request by qparis**

### CODE REVIEW

**Comment by qparis** [comment]
capture d ecran 2017-06-03 a 14 39 24

**Comment by plata** [comment]
Why does this contain the changes from #861 again?

**Comment by qparis** [comment]
Because I needed to merge the master to my branch to resolve the conflicts. As the commit are not the same (because of the squash), GitHub seems to be messing up.
It should merge fine

**Comment by plata** [comment]
Ok. Is it on purpose that the app name is not shown as title anymore?

**Comment by qparis** [comment]
Where?

**Comment by plata** [comment]
It used to be above "type: WINE". However it's not in master currently as well. I think it might make sense to have it back again. Imagine if you have many shortcuts in your library and scroll through it, it might not be clear which one you have selected.

**Comment by plata** [comment]
You can check in #801 how it used to look like.

**Comment by qparis** [comment]
I have no idea why it is not shown

**Comment by plata** [comment]
I will approve this PR but it would be nice if you could check why the title is missing.

**Pull request merged**
