### PR TITLE
moved shortcut buttons to details panel

### PR DESCRIPTION
**Pull request by plata**
shortcut buttons

### CODE REVIEW

**Comment by madoar** [comment]
Maybe we should integrate the buttons in the layout of the details view:
```
Run            Run button
Close         Close button
Uninstall     Uninstall button
```
What do you think?

**Comment by plata** [comment]
Like this (I don't like it)?
layout

**Comment by madoar** [comment]
No the other way around, the icons should be on the right side

**Comment by plata** [comment]
Doesn't look better in my opinion:
icon right

**Comment by madoar** [comment]
and if you do a right alignment for the labels?

**Comment by plata** [comment]
align right

**Comment by madoar** [comment]
@qparis which look do you think looks best?^^

**Comment by madoar** [comment]
@qparis can you please take a look at this too?

**Comment by qparis** [comment]
That last propositions do not look very natural for me. What about trying to make the icons bigger and to put the text under each one?

**Comment by plata** [comment]
Like this?

big icons

**Comment by plata** [comment]
I still prefer the first approach.

**Comment by madoar** [comment]
@plata what about this:
7d40fcee-4479-11e7-984f-ccc52b8170a9

**Comment by plata** [comment]
Better. But still a bit too much "in your face" in my opinion. Maybe we should just merge this until we have a better idea (the functionality is working).

**Comment by qparis** [comment]
Just reduce the size of the icons a little bit

**Comment by plata** [comment]
Like this?
smaller buttons

**Comment by qparis** [comment]
Yes, except the fact that the texts are not aligned

**Comment by plata** [comment]
That's just a quick GIMP. I'll move this to #852 to fix it there.

**Pull request merged**
