### PR TITLE
Code CleanUp

### PR DESCRIPTION
**Pull request by Tomahna**
This should fix most minor sonar issues and some major ones.

### CODE REVIEW

**Comment by qparis** [comment]
Thanks :) 
What IDE are you using? I think we should set up some conventions for the imports

**Comment by qparis** [comment]
ok to test

**Comment by Tomahna** [comment]
I'm on eclipse, and it would be indeed nice to have some conventions on formatting and stuff like that.

**Comment by qparis** [comment]
My settings: 
* import all other imports
Blank Line
* import javax.*
* import java.*
Blank Line
* import static all other imports

**Comment by Veske** [comment]
I think we could use a official formatter.xml for the project that every dev ought to use. IntelliJ users could use the Eclipse formatter plugin and load the formatter.xml with that.

**Comment by Tomahna** [comment]
I strongly agree. If you decide you want specific format, you should put it in the repository. Anyway you should document it in the ReadMe.

A lot of people don't like wildcards in imports though.

**Comment by qparis** [comment]
Can you include your xml file? Thanks

**Comment by Tomahna** [comment]
Sure.

As github refuse xml i changed the extension to txt. That's my profile for cleanup and formater.


[POL_Formater_Profile.txt](https://github.com/PlayOnLinux/POL-POM-5/files/34598/POL_Formater_Profile.txt)
[POL_CleanUp_Profile.txt](https://github.com/PlayOnLinux/POL-POM-5/files/34599/POL_CleanUp_Profile.txt)

**Comment by qparis** [comment]
Can you fix the conflict please? :) Thanks
I'm suprised that github does not allow xml files, as we already have a pom.xml file on the root

**Pull request closed without merging**
