### PR TITLE
Added a "refresh Repositories" button to the repository settings

### PR DESCRIPTION
**Pull request by madoar**
This PR introduces a new "refresh Repositories" button to the repository settings.

grafik

### CODE REVIEW

**Comment by plata** [comment]
Can't we do that automatically? E.g. set a flag and update the repositories when the "Apps" tab is opened the next time.

**Comment by madoar** [comment]
I'm not sure we want that, because the refresh may take a while until it's done.
Especially if you add additional repositories.

**Comment by plata** [comment]
That's true. But on the other hand you will not add repositories if you do not want to use them. Therefore we can assume that any change in the repository settings shall trigger an update. To avoid updating several times because you add/delete multiple repositories, I suggested the flag.

**Comment by madoar** [comment]
I think you've misunderstood for what I would use this button.
I would use it if I know or think to know, that the remote repository has a more up to date version of a script than my local copy.
Then I can use this button to refresh the data without the need to restart POL 5.

**Comment by plata** [comment]
Ah ok. I guess we need some explanatory text for this then.

**Comment by madoar** [comment]
What would you suggest?

**Comment by plata** [comment]
Maybe something like: "Fetch updates for the repositories to retrieve the newest script versions"? It has to be clear but at the same time understandable for the average user.

**Comment by madoar** [comment]
Should this be added as a legend text or as a tooltip?

**Comment by plata** [comment]
I would suggest a two column layout.

**Comment by madoar** [comment]
Ok, I just changed the code to use a two column layout:
grafik

**Comment by plata** [comment]
Shouldn't the legend for the priority be above?

**Comment by madoar** [comment]
I thought it's better to first show all the different settings the user can change, then at the bottom we show the legend for all these settings.
Currently we have only one point to show for the legend, therefore it only contains the priority information.

If needed I can change the order, that the priority information is shown directly below the repositories.
What do you think?

**Comment by plata** [comment]
I think the legend belongs to the repository list.

**Comment by madoar** [comment]
Like this?
grafik

**Comment by plata** [comment]
Yes, that's better.

**Comment by madoar** [comment]
@plata, @qparis is there anything left to do for this PR?
Otherwise it would be nice to see this merged, because I want to refactor the settings tab soon :)

**Pull request merged**
