### PR TITLE
fixed wizard button width

### PR DESCRIPTION
**Pull request by plata**
Before:
before

Now:
now

### CODE REVIEW

**Comment by plata** [comment]
Yes that's probably right.

**Comment by qparis** [comment]
I would prefer the buttons to have the same size

**Comment by plata** [comment]
Yes. But if I have the choice between the text is readable and the buttons have the same size, I'll go for readable.

**Comment by madoar** [comment]
@qparis I agree with @plata for these two buttons. I think it's another topic when we add images to the equation.

**Pull request merged**
