### PR TITLE
Added a test for the initialisation of the AppConfiguration class

### PR DESCRIPTION
**Pull request by madoar**
Ok, this PR introduces a test for the Initialisation of the AppConfiguration.
The problem with this approach is, that it opens a gui-window, and I don't know if jenkins supports this...
If someone has a better approach or understands the API of testfx better than me, I'm open for suggestions :)

### CODE REVIEW

**Comment by plata** [comment]
Sorry, never used testfx until now so I cannot help. Nevertheless I think it's a useful approach. We will find out in a minute if Jenkins can do this.

**Comment by plata** [comment]
ok to test

**Comment by plata** [comment]
Well, there you have it...

**Comment by plata** [comment]
If you search for "headless testing JavaFX" you find some suggestions how to make it work. 
E.g.
- [Headless testing with JavaFx and TestFx](https://stackoverflow.com/questions/27403410/headless-testing-with-javafx-and-testfx)
- [Headless UI Testing with TestFX and JavaFX 8](https://ustesis.wordpress.com/2014/04/23/headless-ui-testing-with-testfx-and-javafx-8/)

**Comment by madoar** [comment]
Ok, how about now?

**Comment by plata** [comment]
Looks good. Let's @qparis also have a look at this.

**Comment by madoar** [comment]
What I'm a bit sceptical about is, the reset jenkins does between two runs. Are the settings (including the created config files etc.) deleted after a run?

**Comment by plata** [comment]
I have no idea.

**Pull request merged**
