### PR TITLE
added engine panel

### PR DESCRIPTION
**Pull request by plata**
engine panel

In preparation for a fix for #528

### CODE REVIEW

**Comment by qparis** [comment]
Not sure we should do it this way: I thing we should be able to différenciate very what versions are installed as in POLv4

**Comment by plata** [comment]
I wanted to mark that on the engine miniature directly (e.g. by showing a green check).
We could also add a filter
- [] only installed
- [] only not installed

**Comment by qparis** [comment]
Great idea

Also the button install should not be shown if the zngine is installed

**Comment by plata** [comment]
Sure. Just wanted to get the basics done first so we can easily add all the other stuff later on.

**Pull request merged**
