### PR TITLE
test/center-item-filter-test:

### PR DESCRIPTION
**Pull request by Veske**
* Created new test class for CenterItemFilter, called CenterItemFilterTest.
       * Tried to cover all the cases that I understood.

### CODE REVIEW

**Comment by qparis** [comment]
ok to test

**Comment by qparis** [comment]
Can you fix your test please? :)

**Comment by qparis** [comment]
ok to test

**Comment by Veske** [comment]
Cannot figure out what is wrong here. The code work on this side when running maven test.

**Pull request merged**
