### PR TITLE
Scale SetupWizard

### PR DESCRIPTION
**Pull request by plata**
fixes:
- JavaFx: SetupWizard doesn't scale #434
- Setup wizard cannot handle long titles #399

### CODE REVIEW

**Comment by plata** [comment]
Not yet finished. Just wanted to know if this approach is ok.

**Comment by qparis** [comment]
Do you have any screenshot ? :)

**Comment by plata** [comment]
The left image does not scale yet and the buttons are on a fixed position, but you can see that the whole size is adjusted.
scaled

**Comment by qparis** [comment]
The approach is good

**Comment by plata** [comment]
@qparis which font is used for "playonlinux"?

**Comment by qparis** [comment]
maven pro

**Comment by plata** [comment]
scaled

**Comment by qparis** [comment]
Awesome, 
The text needs to be rescaled

**Comment by plata** [comment]
Which text?

**Comment by qparis** [comment]
The presentation text. Does it need to be rescaled

**Comment by qparis** [comment]
Do you want to merge it now or do you want to also test all the steps?

**Comment by plata** [comment]
Like this?

small:
small

large:
large

**Comment by plata** [comment]
I checked several of the steps. Should be ok in most cases.

**Comment by qparis** [comment]
Yep

**Comment by qparis** [comment]
Have you checked browse?

**Comment by plata** [comment]
Yes. I checked browse, wait, menu, textbox, message. Maybe there is a small error hidden somewhere, but in general it should be fine.

Just let me check one small thing before merge: What happens if the window is too small to show the text?

**Comment by qparis** [comment]
Don't know. Also, don't forget to check progressbar ? :)

**Comment by plata** [comment]
No ;). It will change the width but keep the height.

**Comment by qparis** [comment]
Tell me when we can merge

**Comment by plata** [comment]
You can. The text will not be readable anymore if the window is too small. I tried using a ScrollPane but then the text is not wrapped anymore...

**Comment by qparis** [comment]
Why not enforcing a minimal window size?

**Comment by plata** [comment]
No. I know applications which do that. Only causes trouble in special cases (e.g. if the enforced size is greater than your screen resolution). But I just found the property to fix the wrapping. Give me one more try :P

**Comment by plata** [comment]
I have a ScrollPane now. But it's not white...

ScrollPane

**Comment by plata** [comment]
Now:

ScrollPane

**Comment by plata** [comment]
What's wrong with the build check? Works for me...

**Comment by Brainzyy** [comment]
@plata It started failing after this: https://github.com/PlayOnLinux/POL-POM-5/pull/440
(Not sure if this is related)

**Comment by plata** [comment]
@Brainzyy yes, that's the reason. Thank you.

**Comment by plata** [comment]
Can I somehow trigger a new build? (without a new commit)

**Comment by qparis** [comment]
Just merge the master to your PR branch and it should work

**Pull request merged**
