### PR TITLE
implemented CachedApplicationsSource

### LINKED ISSUE #607: Implement CachedApplicationSource
The CachedApplicationSource shall make sure that an application source is loaded only once. See GitApplicationsSource.

### PR DESCRIPTION
**Pull request by plata**
fixes #607

### CODE REVIEW

**Comment by plata** [comment]
Sorry what?

**Comment by qparis** [comment]
Unit Test *

**Comment by plata** [comment]
Can I check in our test environment that `fetchInstallableApplications` of the passed ApplicationsSource is called only once? I know it is possible with Mockito mocks.

**Comment by qparis** [comment]
Try verify(mock.method(), once())

**Pull request merged**
