### PR TITLE
show shortcut details in library

### PR DESCRIPTION
**Pull request by plata**
library details

This could also be used to show hints (e.g. for Prince of Persia The Sands of Time: "do not enable fog in the graphic settings").
Maybe we could also change the shortcut from here (e.g. debug level).

### CODE REVIEW

**Comment by madoar** [comment]
I like it, but I think @qparis should decide this.

**Comment by plata** [comment]
Yes, definitely @qparis should decide.

**Comment by qparis** [comment]
This is awesome. I just think we could improve a little bit the presentation of the identity card. What do you think?

**Comment by plata** [comment]
What do you mean by "identity card"?

**Comment by plata** [comment]
presentation

**Comment by madoar** [comment]
@plata this PR seems to have conflicts

**Comment by plata** [comment]
@madoar @qparis can we merge this? I would like to move the run, close and uninstall button to the details panel in a new PR.

**Comment by madoar** [comment]
I think this PR can be merged, but I'm not sure what @qparis meant with the improvement of identity card presentation.

**Comment by plata** [comment]
I think he meant the look of the details panel. I improved that a bit and we can still update it later on.

**Pull request merged**
