### PR TITLE
replaced header with TabPane, fixed scaling of content

### PR DESCRIPTION
**Pull request by plata**
tabs

This pull request  also fixes: Fix scaling of content when window is scaled #355

### CODE REVIEW

**Comment by qparis** [comment]
Can you show with the default theme please ? :)

**Comment by plata** [comment]
defaultTheme

**Comment by qparis** [comment]
Thanks :)

We need to leave the default (gray) tabbar style here, it does not look good otherwise 

Can you add a class to the header tab pane ?

**Comment by plata** [comment]
You mean for the "My applications" TabPane?

**Comment by qparis** [comment]
No the other one, so that the look of the others tab panes (include the "My Application" one) does not change

**Comment by plata** [comment]
Ok. That was what I meant ;)

**Comment by qparis** [comment]
Even in the CSS file?

**Comment by plata** [comment]
Well, I don't really now how to set e.g. `.tab-header-background`. I would like to set the style for the complete pane but I don't think that's possible.

**Comment by qparis** [comment]
Let me try

**Comment by qparis** [comment]
Fixed in pull request #361

**Comment by plata** [comment]
Weird. I had tried pretty much the same...

**Pull request merged**
