### PR TITLE
wrap side bar title

### PR DESCRIPTION
**Pull request by plata**
Before:
before

Now:
wrap

### CODE REVIEW

**Comment by qparis** [comment]
Can you send the whole screenshot please?

**Comment by plata** [comment]
Before:
before

Now:
wrap

**Comment by qparis** [comment]
What if it takes 10 lines to show the name of the game?

**Comment by plata** [comment]
Then it will take 10 lines. To be hones I think that this is really a rare case which will look strange anyways. Many games need two lines so at least those should look ok.

**Pull request merged**
