### PR TITLE
Rewrote InstallWindow's mainScene with automatic sizing.

### PR DESCRIPTION
**Pull request by seijikun**
I rewrote InstallWindow's mainScene with automatic sizing by using the BorderPane and its regions.

### CODE REVIEW

**Comment by qparis** [comment]
Awesome!

**Comment by qparis** [comment]
I reverted your change so that we can fix a small issue. Feel free to have a look. Apart from that details, good job!

**Comment by seijikun** [comment]
The miniature would not be a problem for the right region. But the checkboxes are.
Would it be ok to move the checkboxes to the bottom of the window (bottom left, below the list)?

**Comment by qparis** [comment]
I am even open to completely redesign the window, for exemple like Ubuntu Software Center or any other. 
If you have some plans, you can suggest :)

Otherwise isn't it possible to put the checkboxes in a GridPane?

**Comment by seijikun** [comment]
I just got an idea of how to do it. :)

**Pull request merged**
