### PR TITLE
prepared generic engines (including install/delete)

### LINKED ISSUE #614: Install wine engine

### LINKED ISSUE #615: Delete wine engine

### PR DESCRIPTION
**Pull request by plata**
Preparation for a generic engine handling as described in #620. 

Includes a generic install/delete.
- fixes #614
- fixes #615
- requires PlayOnLinux/Scripts#175

The EngineVersionDTO is not yet generic. It should contain an engine specific userData Map like EngineDTO. However, this requires a change in the Wine JSON format (Wine specific information like Mono/Gecko file should be contained in userData).

### CODE REVIEW

**Comment by qparis** [comment]
Do you have the diagram class of the new DTO set?

**Comment by plata** [comment]
No. But it didn't really change much. WineVersionDistributionDTO and WineVersionDTO got renamed to EngineSubCateoryDTO and EngineVersionDTO. EngineCategoryDTO has been added on top to distinguish the engine categories (Wine, ScummVM...).

**Comment by qparis** [comment]
What IDE are you using?

**Comment by plata** [comment]
IntelliJ IDEA (the community version does not have the UML tools).

**Comment by qparis** [comment]
We have free pro license if you are interested

**Comment by plata** [comment]
Unless I shall do more UML, I think the community is enough for me ;)

**Comment by qparis** [comment]
The pro edition allows you to use Maven, and test coverage

**Comment by plata** [comment]
I can use Maven build in the community edition as well. What can I do more in pro? BTW: Could you add the descriptions about code formatter etc in README also for IDEA?

**Comment by qparis** [comment]
The code formatter settings should be directly committed 

Here are the main differences https://www.jetbrains.com/idea/features/editions_comparison_matrix.html

**Comment by plata** [comment]
Oh. JS support would be nice for the scripts.

What do you mean the formatter settings should be committed? Is it possible to add a beautify step to the maven build?

**Comment by qparis** [comment]
This is possible with maven but it would lead to a ping-pong effect if the ide is not well configured.

I suggest integrating the code formatting settings in the source repository (I'm pretty sure that it is already done for at least eclipse)

**Comment by plata** [comment]
I never did code formatting for Java so I cannot tell. For C++ integrating the beautifier into the build system is quite nice as you do not have to care about anything.

**Comment by qparis** [comment]
Well you have to because you are not obliged to use maven to POL. Also, you could have maven de synchronized with the IDE which would lead to pollution commits.

Before thinking about the tool we are going to use, we need to think about the way the convention are described (xml codestyle files ?)

**Comment by plata** [comment]
Let's continue this in  #627.

**Pull request merged**
