### PR TITLE
Add filter functionality for the unused checkboxes inside the "Apps" tab

### LINKED ISSUE #731: Implement functionality for the filter checkboxes in the "Apps" tab
Currently we have 3 checkboxes in the sidebar of the "Apps" tab, that do absolutely nothing.
We should add some functionality to them.

### PR DESCRIPTION
**Pull request by madoar**
Fixes #731.
grafik
grafik
grafik
grafik
grafik
grafik
grafik

### CODE REVIEW

**Comment by plata** [comment]
Does it make sense to have "Free" and "Commercial"? The only use case for this would be to find only commercial apps but why should you do that? In my opinion it would be sufficient to have only one of them.

**Comment by madoar** [comment]
grafik
grafik
grafik
grafik

**Comment by plata** [comment]
Good. What's the default setting for the checkboxes? I think "Commercial" should be checked by default and the other ones not. Are the filters saved and reloaded on the next startup?

**Comment by madoar** [comment]
The default setting is like you described, with only "Commercial" checked by default.
The filters aren't saved and reloaded on the next startup.

**Comment by plata** [comment]
Just tried it. The "Testing" filter does not seem to work.

**Comment by madoar** [comment]
What do you mean with not work? Does it nothing or something unexpected?

**Comment by plata** [comment]
It did not show an application which has the following settings in its json even though I selected "Testing":
```JSON
"compatibleOperatingSystems": [],
"testingOperatingSystems": ["LINUX"],
```

**Comment by madoar** [comment]
Did you maybe use some other filters too, which influences your result? 
The "Testing" checkbox only has an effect on your result if it's not selected.
Otherwise it would be good to add some debug output to the filter method in `ApplicationFilter`.

**Comment by plata** [comment]
I think I also had commercial. What do you mean with "only has an effect on your result if it's not selected."?

**Comment by madoar** [comment]
This is how the "testing" checkbox is used during the `filter` call:
```
+        /*
+         * If "Testing" is not selected don't show games that are currently in a testing stage
+         */
+        if (!containTestingApplications.getValue()) {
+            result &= application.getScripts().stream()
+                    .anyMatch(script -> script.getTestingOperatingSystems().isEmpty());
+        }
```

**Comment by plata** [comment]
Shouldn't it be `if (!containTestingApplications.getValue()) {` (without the `!`)? You only need the `!` for commercial because commercial = !free.

**Comment by madoar** [comment]
No, because:

- if you don't select "Testing", you want to see all applications that aren't in a testing stage (which is the case if the testing operating systems array/list is empty)
- if you select "Testing", you want to see all applications

right?

**Comment by plata** [comment]
Yes. I've been mistaken. Anyways, I just figured out that the following works:
```JSON
"compatibleOperatingSystems": ["LINUX"],
"testingOperatingSystems": ["LINUX"],
```

**Pull request merged**
