### PR TITLE
Correct some Java convention

### PR DESCRIPTION
**Pull request by Tutul-**
like "private static final Logger LOGGER = Logger.getLogger(<className>.class);" !

(not important or urgent so take your time)

### CODE REVIEW

**Comment by yawkat** [comment]
Loggers are actually often exempt to capitalization :) I guess it doesn't make too much of a difference though.

**Comment by Tutul-** [comment]
it's just a convention, if a declaration is static and final (http://docs.oracle.com/javase/tutorial/java/nutsandbolts/variables.html) but it's only the appearance, no performance impact so that is why it is neither important nor urgent need :)

**Comment by qparis** [comment]
In general, we do not code "just to please" sonarqube 

There must be a valid reason that will improve the code quality.

**Comment by Tutul-** [comment]
for me, respect the langage convention is a bit important. But you decide :)

**Comment by qparis** [comment]
The convention is not defined at a language level but at a project level

**Comment by qparis** [comment]
(But as long as we keep the same convention (ie LOGGER) for the whole project, it is fine)

**Pull request merged**
