### PR TITLE
Sort engines

### PR DESCRIPTION
**Pull request by plata**

### CODE REVIEW

**Comment by plata** [comment]
Please merge #473 first.

**Comment by Brainzyy** [comment]
@plata I think you branched off the wrong branch, because the commits of #473 are in this PR as well.

**Comment by plata** [comment]
@Brainzyy I know... I did #473 on my master yesterday because it's really small and I thought it would be merged immediately. That's why I said that #473 should be merged first.

**Comment by Brainzyy** [comment]
@plata Ah okay, that's fine, just wanted to let you know :)

**Comment by plata** [comment]
@Brainzyy always good to have someone reviewing ;)

**Comment by qparis** [comment]
I don't understand the purpose of this

Can you explain?

**Comment by plata** [comment]
The engines are not sorted. If you look at the tabs you get something like 2.0rc5, 2.0rc3, 2.0rc4. 

If you look at the old code, it's trying to sort the versions (`WineVersionDTO`) by `WineVersionDistributionDTO`. That's not working.

**Comment by qparis** [comment]
Then we need to enhance version comparator I think

**Comment by plata** [comment]
Don't know. For me the simple alphabetical sorting would be enough. At least it's obvious to the user how the sorting is done.

**Comment by qparis** [comment]
If you do so, wine-1.9.10 will be before wine 1.9.9 and not after

**Comment by plata** [comment]
You're right.

I don't know how 2.0-rc4 is handled with regards to intermediate/low number.

**Comment by qparis** [comment]
We can add a unit test asking 2.0-rc4 to be higher than 1.9.10
This is the way it should be done I think

**Comment by plata** [comment]
The problem is that "-" is used to denote a description so "rc4" is seen as description instead low number.

**Comment by plata** [comment]
Should be ok now.

**Comment by Brainzyy** [comment]
@plata The staging engines now sort correctly. But the upstream engines have Wine1.5.27-NeedforSpeed as the first engine, which is not correct.

**Comment by plata** [comment]
@Brainzyy that's because the engine is named 15.27 (the . between 1 and 5 is missing). Therefore, the big version is 15 which is > 2. So the sorting is correct, the mistake is in the engine name.

@qparis can you fix it in <http://phoenicis.playonlinux.com/index.php/wine?os=linux>?

**Pull request merged**
