### PR TITLE
Cleanup of the phoenicis-apps project

### PR DESCRIPTION
**Pull request by madoar**
This PR partially addresses #686 and #659.
In addition it contains the following:
- moved the repository classes to a separate `repository` package inside the phoenicis-apps project
- added `toString` methods for the most often used repository types
- added equals and `hashCode` methods for the NullRepository
- removed the filter classes from the phoenicis-apps project. In my opinion detailed filters should be implemented in the projects, that make use of the repositories. The only exception to this is the operation system filter, which is still managed by the `FilterRepository`.

### CODE REVIEW

**Comment by plata** [comment]
Why is the `MultipleRepository` deleted and added? Didn't you use `git mv` for this class (all others seem all right)?

**Comment by madoar** [comment]
I didn't use `git mv`, I moved them in `IntelliJ` and added the changes afterwards with `git add .`, not sure how git perceives this.

**Comment by plata** [comment]
I think it doesn't realize it. Just wondering why it worked for the other classes.

**Comment by madoar** [comment]
Ah, I know why it was interpreted as deleted. Take a look at the indention. It's either done by tabs or using 8 spaces, while the other files are indented with 4 spaces.

**Comment by plata** [comment]
We should have a guideline about the required indention somewhere. I also noticed that my IntelliJ started complaining about 4/8 spaces some time ago.

**Comment by plata** [comment]
Seems like 8 is correct:
```xml
<setting id="org.eclipse.jdt.core.formatter.indentation.size" value="8"/>
```

**Comment by madoar** [comment]
I know that the "official" code format is 8, but I think 8 is too much.
As far as I know we currently find both an indention of 8 and of 4 in the code, do you know what is more often used?
I myself would suggest to go with an indention of 4.

**Comment by plata** [comment]
I don't know which is used more often. I'm just surprised why this is not changed automatically by the `maven-java-formatter-plugin`.

**Comment by madoar** [comment]
In addition it seems like the maven formatter plugin ignores the indention too, see #765 for the corresponding issue.

**Comment by plata** [comment]
I'm not so sure about the `repository` folder. E.g. why is `DefaultRepositoryManager.java` in `apps` and not in `repository`, why are the tests not moved to a `repository` folder?
Moreover, I think it would be better to rename `apps` to `repository` directly. Actually, the categories contain not only apps but also functions/verbs. Have a look at #622 for more background.

**Comment by madoar** [comment]
I've moved the `Repository` implementations in a separate package, to make them easier to see and find.
The `RepositoryManager` isn't a repository itself (as can be seen by the fact that it doesn't implement `Repository`) and is therefore not contained in the new package.

**Comment by plata** [comment]
I see. Nevertheless, I think that the `apps` folder is a bit misleading and should be named `repository` instead. Then we would have `repository/repository`.

**Comment by plata** [comment]
Why didn't the formatter apply automatically before? It's supposed to run whenever you build.

**Comment by madoar** [comment]
I tested it in `IntelliJ` and only run `mvn clean test`. So I guess that intellij doesn't automatically run the plugin?

**Comment by plata** [comment]
I think the default build step for the plugin is validate. So it's not working as I would expect.

**Comment by madoar** [comment]
I would suggest to solve the maven formatter plugin problems in another PR and view this one without the formatting problematics.

**Comment by plata** [comment]
Yes.

**Comment by plata** [comment]
Approved but we should clarify the naming of the module (app vs repository).

**Comment by madoar** [comment]
You're right app(s) is maybe not the right term to use here.
I'm open for suggestions.

**Comment by plata** [comment]
We can discuss that later in #770.

**Pull request merged**
