### PR TITLE
translate app categories

### PR DESCRIPTION
**Pull request by plata**

### CODE REVIEW

**Comment by plata** [comment]
It's the same issue as in #872: If we use `tr(category.getName())`, we have to provide the translations as part of the Phoenicis software. As a result, it would not be possible for the users to add their own (translated) categories.

**Comment by qparis** [comment]
For this reason, it is really clear for me that we really need to find a way to use the same translation framework for Java and Javascript.
It makes a lot more sense

**Comment by madoar** [comment]
This PR has a conflict.

**Comment by plata** [comment]
PR is outdated. I'm just leaving it open for now because I might need some snippets from it. Will close it later.

**Pull request closed without merging**
