### PR TITLE
removed obsolete HiDPI theme

### PR DESCRIPTION
**Pull request by plata**
it was still shown as option in the settings

### CODE REVIEW

**Comment by madoar** [comment]
What about the css files belonging to the HIDPI theme?
Should we remove them at this point too?

**Comment by plata** [comment]
The are removed already. I've just forgotten the settings when I did that.

**Comment by madoar** [comment]
Then I think we can merge this, but I'm not sure if I should decide this (in general)?

**Comment by plata** [comment]
No idea. I always try to do it this way: If the change does not have a big impact, I decide. If it affects the structure of the software, wait for @qparis OK.

**Comment by madoar** [comment]
Then let's go with this approach. I think this has a small impact^^

**Comment by madoar** [comment]
Ok not sure how the merging works, so that you're marked as the author....

**Comment by plata** [comment]
You should squash and merge and fill the title and description properly.

**Pull request merged**
