### PR TITLE
use URI for EngineCategoryDTO icon

### PR DESCRIPTION
**Pull request by plata**

### CODE REVIEW

**Comment by madoar** [comment]
Does this require some changes to the `Scripts` repository?
I'm kind of missing the code that creates an `EngineCategoryDTO` object.

**Comment by plata** [comment]
I don't think so. It is created in `EnginesSource`: 
```Java
EngineCategoryDTO wine = new EngineCategoryDTO.Builder()
```

**Comment by madoar** [comment]
Which means that we're currently setting no icon for the engines?

**Comment by plata** [comment]
Yes. It's using the default `WINE_MINIATURE` in `StaticMiniature`.

**Comment by plata** [comment]
see #792

**Pull request merged**
