### PR TITLE
hotfix: cannot start/uninstall apps

### PR DESCRIPTION
**Pull request by plata**
hotfix to restore basic usability of Phoenicis until #939 is fixed

### CODE REVIEW

**Comment by plata** [comment]
I tried but it didn't work. Maybe I just didn't do it right but I don't know how to do it.

**Comment by qparis** [comment]
What error do you have when you add @Safe annotation?

**Comment by plata** [comment]
There was no error. It just didn't work. Also I'm not quite sure where I have to add it.

**Comment by qparis** [comment]
On top of the class

**Comment by plata** [comment]
It's an interface.

**Comment by qparis** [comment]
Add it on the implementation

**Comment by plata** [comment]
I cannot find any implementation (it's `UiQuestionFactory`).

**Comment by qparis** [comment]
Implementations are anonymous class currently. They must be promoted to proper class to be annotated

**Comment by plata** [comment]
Ok. There's a couple of place where this is the case and currently the software is just not working. In my opinion we should do the hotfix now and the test everything before we enable the security stuff. Also we should have tests which avoid something like this in the future.

**Comment by qparis** [comment]
I don't agree that we should merge this hotfix, it will require more work than fixing the two beans that we have missed. 
Also, if we merge this, this will hide us any other problems that could exist
Currently, POL-POM-5 is not released so this is normal that we have such problems in the master.

**Comment by madoar** [comment]
I agree with @qparis, I think we should prefer a longterm solution instead of a short term solution.

**Pull request closed without merging**
